site_name: Carl-bot Documentation
theme: 
  name: 'material'
  logo: 'images/googleturtle.svg'
  favicon:
    'images/favicon.ico'
  features:
    - tabs
    - instant
  palette:
    scheme: preference
    primary: 'Blue Grey'
    accent: 'Cyan'
  font:
    text: 'Roboto'
    code: 'Fira Mono'
  
repo_name: 'carlbot-docs'
repo_url: 'https://github.com/CarlGroth/carlbot-docs'

extra:
  social:
    - icon: 'fontawesome/solid/globe-americas'
      link: 'https://carl.gg'
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/CarlGroth'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/Carlgrrr'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - pymdownx.betterem:
      smart_enable: all

google_analytics:
  - 'UA-126357432-1'
  - 'auto'

copyright: 'Copyright &copy; 2022 Botlabs (support@botlabs.gg)'
