site_name: Carl-bot Documentation
# nav:
#   - Dashboard: 'https://carl.gg'
#   - Discord: 'https://carl.gg/discord'
#   - GitHub: 'https://github.com/CarlGroth/Carl-Bot'
#   - Patreon: 'https://patreon.com/carlbot'


# nav: 
# - Home: index.md
# - Roles: 
#   - /roles/reaction-roles
#   - 'Reaction Roles': /roles/reaction-roles
#   - 'Role Management': /roles/role-management
#   - 'Autoroles': /roles/autoroles-and-delayed-autoroles
# - 'Tags and Triggers':
#   - 'Tags': /tags-and-triggers/tags
#   - 'Tags - Advanced Usage': /tags-and-triggers/tags-advanced-usage
#   - 'Triggers': /tags-and-triggers/autoresponses-trigger-words
# - Config:
#   - 'Command Permissions': /config/managing-commands
#   - Prefixes: /config/prefixes
# - Moderation:
#   - Moderation: 
#     - moderation: /moderation/moderation.md
#   - 'Automod': 
#     - /moderation/automod
# - Misc:
#   - Animals: /misc/animals
#   - Silly/Useless: /misc/silly-useless
# - Logging:
#   - Logging: /logging/logging
#   - Modlogs: /logging/modlogs
#   - 'Welcome Messages': /logging/welcome-and-leave-messages
# - Utilities:
#   - Announcements: /utilities/announcements
#   - Embeds: /utilities/embeds
#   - Highlights: /utilities/highlights-pager
#   - Reminders: /utilities/reminders-timers
#   - Starboard: /utilities/starboard
#   - Suggestions: /utilities/suggestions
#   - 'Twitch Notifications': /utilities/twitch-notifications
#   - Miscallaneous: /utilities/uncategorized-utilities 
# - Music:
#   - Music: /music/music
  

# nav: 
#   - Home: ../
#   - Tags: /tags-and-triggers/tags
#   - Animals: /misc/animals

theme: 
  name: 'material'
  logo:
    'images/googleturtle.svg'
  favicon:
    'images/favicon.ico'
  feature:
    tabs: true
  palette:
    primary: 'Blue Grey'
    accent: 'Cyan'
  font:
    text: 'Roboto'
    code: 'Fira Code'
  
repo_name: 'carlbot-docs'
repo_url: 'https://github.com/CarlGroth/carlbot-docs'

extra:
  social:
    - type: 'discord'
      link: 'https://carl.gg'

markdown_extensions:
  - admonition

google_analytics:
  - 'UA-126357432-1'
  - 'auto'

copyright: 'Copyright &copy; 2018 - 2019 Carl'
